<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(CuriosusTargetFrameworks)</TargetFrameworks>

        <PackageId>Curiosus.DataAnnotations</PackageId>
        <Title>Curiosus.DataAnnotations</Title>
        <Description>Custom data annotations and validator.</Description>
        <Summary>Custom data annotations and validator.</Summary>
        <PackageTags>Curiosus; data annotations; validation</PackageTags>
        <Language>English</Language>

        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>

        <Authors>$(CuriosusAuthors), Andrei Vinogradov (@anri-vin)</Authors>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/curiosus-dev/Curiosus.Utils</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Utils</RepositoryUrl>
        <PackageReleaseNotes>https://github.com/curiosus-dev/Curiosus.Utils/tree/master/src/Misc/Curiosus.DataAnnotations/CHANGELOG.md</PackageReleaseNotes>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\Curiosus.DataAnnotations.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.ComponentModel.Annotations" />
    </ItemGroup>

</Project>
