<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(CuriosusTargetFrameworks)</TargetFrameworks>
        
        <PackageId>Curiosus.FileDataReaderWriters.SylvanCsv</PackageId>
        <Title>Curiosus.FileDataReaderWriters.SylvanCsv</Title>
        <Description>Sylvan realization for working with csv files</Description>
        <Summary>Read and write to csv file. Low memory consumption due to bufferization.</Summary>
        <PackageTags>Curiosus; FileDataReaderWriters; Sylvan; siisltd</PackageTags>
        <Language>English</Language>

        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <PackageVersion>2.0.0</PackageVersion>

        <Authors>Max Markelow (@markeli), Andrei Vinogradov (@anri-vin), Andrey Ioch (@DevCorvette), Timur Sidoriuk (@shockthunder)</Authors>
        <Company>SIIS Ltd</Company>
        <Copyright>SIIS Ltd, 2026</Copyright>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/curiosus-dev/Curiosus.Utils</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Utils</RepositoryUrl>
        <PackageReleaseNotes>https://github.com/curiosus-dev/Curiosus.Utils/tree/master/src/FileData/Curiosus.FileDataReaderWriters.SylvanCsv/CHANGELOG.md</PackageReleaseNotes>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <PackageIcon>siisltd.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\..\siisltd.png" Pack="true" PackagePath="\" />
    </ItemGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\Curiosus.FileDataReaderWriters\Curiosus.FileDataReaderWriters.csproj"/>
        <PackageReference Include="Sylvan.Data.Csv" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\Curiosus.FileDataReaderWriters.Sylvan.xml</DocumentationFile>
    </PropertyGroup>
</Project>
