<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>$(CuriosusTargetFrameworks)</TargetFrameworks>

        <PackageId>Curiosus.RequestProcessing.RabbitMQ</PackageId>
        <Title>Curiosus.RequestProcessing.RabbitMQ</Title>
        <Description>Services to receive and process reqesuts/events from RabbitMQ.</Description>
        <Summary>Services to receive and process requests/events from RabbitMQ.</Summary>
        <PackageTags>Curiosus; Request; Queue; Workers; Processors; RabbitMQ; RPC; AMQP; Messaging</PackageTags>
        <Language>English</Language>

        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <PackageVersion>2.0.0</PackageVersion>

        <Authors>Max Markelow (@markeli), Andrei Vinogradov (@anri-vin)</Authors>
        <Company>SIIS Ltd</Company>
        <Copyright>SIIS Ltd, 2026</Copyright>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/curiosus-dev/Curiosus.Utils</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Utils</RepositoryUrl>
        <PackageReleaseNotes>https://github.com/curiosus-dev/Curiosus.Utils/tree/master/src/RequestProcessing/Curiosus.RequestProcessing.RabbitMQ/CHANGELOG.md</PackageReleaseNotes>

        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>
    <ItemGroup>
      <ProjectReference Include="..\..\Messaging\Curiosus.RabbitMQ\Curiosus.RabbitMQ.csproj" />
      <ProjectReference Include="..\Curiosus.RequestProcessing\Curiosus.RequestProcessing.csproj" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <DocumentationFile>bin\Release\Curiosus.RequestProcessing.RabbitMQ.xml</DocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <PackageIcon>siisltd.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\..\siisltd.png">
            <Pack>true</Pack>
            <PackagePath>/</PackagePath>
            <Link>siisltd.png</Link>
        </None>
    </ItemGroup>

</Project>
