<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(CuriosusTargetFrameworks)</TargetFrameworks>

        <PackageId>Curiosus.Localization.MVC</PackageId>
        <Title>Curiosus.Localization.MVC</Title>
        <Description>Classes for localizing applications in more efficient way than Microsfot's way.</Description>
        <Summary>Classes for localizing applications in more efficient way than Microsfot's way.</Summary>
        <PackageTags>Curiosus; Localization; MVC</PackageTags>
        <Language>English</Language>

        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>

        <Authors>$(CuriosusAuthors), Andrei Vinogradov (@anri-vin)</Authors>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/curiosus-dev/Curiosus.Utils</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Utils</RepositoryUrl>
        <PackageReleaseNotes>https://github.com/curiosus-dev/Curiosus.Utils/tree/master/src/Localization/Curiosus.Localization.MVC/CHANGELOG.md</PackageReleaseNotes>

        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Curiosus.Localization\Curiosus.Localization.csproj" />
    </ItemGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

</Project>
