<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(CuriosusTargetFrameworks)</TargetFrameworks>

        <PackageId>Curiosus.EMail</PackageId>
        <Title>Curiosus.EMail</Title>
        <Description>Base classes for working with EMails</Description>
        <Summary>Base EMail sender, EMail adress validation and attriburtes.</Summary>
        <PackageTags>Curiosus; EMail</PackageTags>
        <Language>English</Language>

        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>

        <Authors>$(CuriosusAuthors), Andrey Ioch (@DevCorvette), Andrei Vinogradov (@anri-vin)</Authors>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/curiosus-dev/Curiosus.Utils</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Utils</RepositoryUrl>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\Curiosus.EMail.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>                                             
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="MimeKit" />
      <PackageReference Include="System.ComponentModel.Annotations" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Misc\Curiosus.Tools\Curiosus.Tools.csproj" />
    </ItemGroup>

</Project>
