<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(CuriosusTargetFrameworks)</TargetFrameworks>

        <PackageId>Curiosus.SMS.Smsc</PackageId>
        <Title>Curiosus.SMS.Smsc</Title>
        <Description>Classes for sending SMS via smsc.ru.</Description>
        <Summary>Classes for sending SMS via smsc.ru.</Summary>
        <PackageTags>Curiosus; SMS; smsc</PackageTags>
        <Language>English</Language>

        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>

        <Authors>$(CuriosusAuthors), Andrei Vinogradov (@anri-vin)</Authors>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/curiosus-dev/Curiosus.Utils</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Utils</RepositoryUrl>

        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\Curiosus.SMS.Smsc.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Configuration\Curiosus.Configuration\Curiosus.Configuration.csproj" />
      <ProjectReference Include="..\Curiosus.SMS\Curiosus.SMS.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Http" />
    </ItemGroup>

</Project>
