<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(CuriosusTargetFrameworks)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageVersion>2.0.0</PackageVersion>
        <Title>Curiosus.SMS.Iqsms</Title>
        <Description>Classes for sending SMS via iqsms.ru.</Description>
        <PackageProjectUrl>https://github.com/curiosus-dev/Curiosus.Utils</PackageProjectUrl>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Utils</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>Curiosus; SMS; iqsms</PackageTags>
        <Authors>$(CuriosusAuthors), Andrey Ioch (@DevCorvette), Andrei Vinogradov (@anri-vin)</Authors>    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Curiosus.SMS\Curiosus.SMS.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="RestSharp" />
    </ItemGroup>

</Project>
