<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(CuriosusTargetFrameworks)</TargetFrameworks>

        <PackageId>Curiosus.RequestProcessing.Postgres</PackageId>
        <Title>Curiosus.RequestProcessing.Postgres</Title>
        <Description>Services to receive and process reqesuts/events from Postgres</Description>
        <Summary>Services to receive and process reqesuts/events from Postgres.</Summary>
        <PackageTags>Curiosus; Request; Queue; Workers; Processors; Postgres; Events; Messaging</PackageTags>
        <Language>English</Language>

        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <PackageVersion>2.0.0</PackageVersion>

        <Authors>$(CuriosusAuthors), Andrei Vinogradov (@anri-vin)</Authors>

        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>

        <PackageProjectUrl>https://github.com/curiosus-dev/Curiosus.Utils</PackageProjectUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/curiosus-dev/Curiosus.Utils</RepositoryUrl>
        <PackageReleaseNotes>https://github.com/curiosus-dev/Curiosus.Utils/tree/master/src/RequestProcessing/Curiosus.RequestProcessing.Postgres/CHANGELOG.md</PackageReleaseNotes>

        <OutputType>Library</OutputType>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <RootNamespace>Curiosus.RequestProcessing.Postgres</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Curiosus.RequestProcessing\Curiosus.RequestProcessing.csproj" />
    </ItemGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <DocumentationFile>bin\Release\Curiosus.RequestProcessing.Postgres.xml</DocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" />
    </ItemGroup>
    
</Project>
